apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mpijobs.kubeflow.org
spec:
  group: kubeflow.org
  version: v1alpha1
  scope: Namespaced
  names:
    plural: mpijobs
    singular: mpijob
    kind: MPIJob
    shortNames:
    - mj
    - mpij
  validation:
    openAPIV3Schema:
      properties:
        spec:
          title: The MPIJob spec
          description: Either `gpus` or `replicas` should be specified, but not both
          oneOf:
          - properties:
              replicas:
                title: Total number of replicas
                description: The GPU resource limit should be specified for each replica
                type: integer
                minimum: 1
            required:
            - replicas
